name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.2.3+33

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pinput: ^2.2.31
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2
  flutter_typeahead: ^3.2.7
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  flutter_inappwebview: 5.7.2+3
  flutter_widget_from_html_core: ^0.8.5+3
  url_launcher: ^6.0.17
  http: ^0.13.4
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.1
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  flutter_facebook_auth: ^4.4.1+1
  photo_view: ^0.14.0
  dotted_border: ^2.0.0+2
  share_plus: ^4.0.4
  custom_map_markers: ^0.0.2+1
  image_compression_flutter: ^1.0.2
  fwfh_text_style: ^2.22.8+1
  card_swiper: ^2.0.4
  expandable_bottom_sheet: ^1.1.1+1
  file: ^6.1.4
  upgrader: ^6.5.0
  file_picker: ^5.3.1

  

 
  
 

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  flutter_inappwebview: 5.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/


  fonts:
    - family: ArbFONTS
      fonts:
        - asset: assets/font/ArbFONTS-GESS.ttf
          weight: 400
        - asset: assets/font/ArbFONTS-GESS.ttf
          weight: 500
        - asset: assets/font/ArbFONTS-GESS.ttf
          weight: 700
        - asset: assets/font/ArbFONTS-GESS.ttf
          weight: 900
  

    - family: Roboto
      fonts:
         - asset: assets/font/Roboto-Regular.ttf
           weight: 400
         - asset: assets/font/Roboto-Medium.ttf
           weight: 500
         - asset: assets/font/Roboto-Bold.ttf
           weight: 700
         - asset: assets/font/Roboto-Black.ttf
           weight: 900

    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
        - asset: assets/font/Cairo-Black.ttf
          weight: 900
